### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by DuncanUszkay1** [mcasper/dogstatsd-rs#27]
The examples in the readme don't work in version 0.6.1. 
If I create a new project and copy the example code:
```
use dogstatsd::{Client, Options};

fn main() {
    let client = Client::new(Options::default());

    // Increment a counter
    client.incr("my_counter", vec![]).unwrap();
}
```
I get a compiler error:
```
Compiling rust-test v0.1.0 (/Users/duncanuszkay/src/github.com/Shopify/rust-test)
error[E0599]: no method named `incr` found for type `std::result::Result<dogstatsd::Client, dogstatsd::error::DogstatsdError>` in the current scope
 --> src/main.rs:7:12
  |
7 |     client.incr("my_counter", vec![]).unwrap();
  |            ^^^^

error: aborting due to previous error
```
It seems that this is due to the fact that the Client::new method returns a result in the newer code. 

Additionally the link to full documentation is out of date:
![Screen Shot 2019-06-20 at 10 11 12 AM](https://user-images.githubusercontent.com/8670351/59855843-c04eea80-9343-11e9-8754-41703d02a003.png)

**Comment by mcasper** [comment]
Hey @DuncanUszkay1, thank you for reporting this! I just pushed a commit that should resolve this: https://github.com/mcasper/dogstatsd-rs/commit/031dea8d215bae865d56dff6237f7e89df18c348

**Comment by mcasper** [comment]
In addition I've just pushed https://github.com/mcasper/dogstatsd-rs/commit/9fb82d1a3a9654f330c9d342edc382cfea29aff8 which fixes the Travis/Github integration for uploading the latest docs to GH pages
